name: 'YAML Validator'
description: 'Validate YAML document against a given schema'
author: 'navikt'

inputs:
  schema_path:
    description: 'Path to the YAML schema to validate against'
    required: true
  document_path:
    description: 'Path to the YAML document to be validated'
    required: true
  validate_file_extension:
    description: 'Validate that all the given documents have a valid YAML file extension'
    required: false
    default: 'no'

runs:
  using: 'docker'
  image: 'docker://navikt/yaml-validator:v2.1'
  args:
    - ${{ inputs.schema_path }}
    - ${{ inputs.document_path }}
    - ${{ inputs.validate_file_extension }}

branding:
  color: purple
  icon: check-circle
